### ISSUE TITLE
Texto CINE Edición 2021

### ISSUE THREAD

**Issue by LuisPiccini** [ospeconTI/AppUOCRA#7]
Va el texto que nos piden poner y reemplazar lo que está.

La #8 Edición de Construir Cine finalizó luego de más de dos semanas de Festival. Las casi 70 películas que ofrecimos gratis para todo el país, lograron encontrar su público online y así lo demuestran los más de 15.000 accesos a las 5 plataformas online que tuvimos este año: Octubre TV, Lumiton Audiovisual, Vivamos Cultura, Cont.ar y Construir Cine.

Después de ser el primer Festival en la región que en el 2020 hizo su versión totalmente digital, este año reconvertimos la virtualidad para llegar a más personas en todo el país. Además de la programación, ofrecimos más de 20 Actividades Especiales en línea que nos permitieron recrear la experiencia del Festival presencial, reuniendo a más de 12.000 personas en entrevistas a cineastas, workshops, keynotes, debates y reflexiones con especialistas de todo el mundo.

**Comment by BrunoMon** [comment]
![image](https://user-images.githubusercontent.com/4459863/121950744-6ade2600-cd30-11eb-9e1c-fe53bab85bcb.png)

Asi quedría la pantalla, si te va cerra el issue y lo pongo on-line
